name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"  # Match semantic versioning tags like v1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "picupup/debian-texlive-full"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/debian-texlive-full:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/debian-texlive-full:${{ github.ref_name }}
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}

